name: SpecialLoot
main: com.github.birdsoftheworld.specialloot.SpecialLoot
version: 0.1.0
api-version: "1.15"
commands:
  addspecialty:
    usage: /addspecialty <specialty> [propertySet]
    permission: specialloot.changespecialties
  listspecialties:
    usage: /listspecialties
    permission: specialloot.listspecialties
permissions:
  specialloot.changespecialties:
    default: op
  specialloot.listspecialties:
    default: true