name: SpecialLoot
main: com.github.birdsoftheworld.specialloot.SpecialLoot
version: 0.1.0
api-version: "1.15"
commands:
  addspecialty:
    usage: /addspecialty specialty
    permission: specialloot.changespecialties
permissions:
  specialloot.changespecialties:
    default: op